### ISSUE TITLE
drive train problemos

### ISSUE THREAD

**Issue by arihantpandey** [6238/2018-robot-code#1]
When I push the joysticks the motors and such spin, but they are in the wrong gear on the gearbox, so there's a loud noise but no motion. As such, we'll need to move the solenoids make sure the gearbox is in the right position. We need to find out which orientation is what we want, and make sure it is set to the right position in the DriveTrainRobotController.java file so the robot moves correctly.

**Comment by abhiInCalif** [comment]
Can we write more details about how the Solenoids need to operate to fix the gear box spinning?

**Comment by arihantpandey** [comment]
I want to set the solenoid in the correct position so that gearboxes engage and the robot moves.
